{% set name = "opentelemetry-instrumentation-flask" %}
{% set version = "0.29b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-flask-{{ version }}.tar.gz
  sha256: c04df46a8e2e8a80f5662bd161a146600c0087e707034d57968cd015c595f190

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.29b0
    - opentelemetry-instrumentation-wsgi ==0.29b0
    - opentelemetry-semantic-conventions ==0.29b0
    - opentelemetry-util-http ==0.29b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.26b1
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.27b0
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.28b0
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.28b1
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.29b0
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0
    # - opentelemetry-test-utils ==0.29b0
    # - markupsafe ==2.0.1
    # - flask <3.0,>=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-flask
  summary: Flask instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
